// File generated by FlutterFire import 'firebase_options.dart';CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// 
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrN575RH2G3NtTjv_fVvAN7uQpDD7bt4Q',
    appId: '1:57355257284:web:4b09fa7badd76c9fdc1091',
    messagingSenderId: '57355257284',
    projectId: 'mynotes-hazem-windows',
    authDomain: 'mynotes-hazem-windows.firebaseapp.com',
    storageBucket: 'mynotes-hazem-windows.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3fS38LCHcZ6ErKAf9hPKwjaa4QqzeAw4',
    appId: '1:57355257284:android:96eb4ecf35896d87dc1091',
    messagingSenderId: '57355257284',
    projectId: 'mynotes-hazem-windows',
    storageBucket: 'mynotes-hazem-windows.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNrWPwlE8x6a3A7SeAhYlnykDfQpf55s',
    appId: '1:57355257284:ios:3c16705b80d95dfcdc1091',
    messagingSenderId: '57355257284',
    projectId: 'mynotes-hazem-windows',
    storageBucket: 'mynotes-hazem-windows.appspot.com',
    iosClientId: '57355257284-s3rp9ot7m69d8g09nmrsnc1p9s8n3ku0.apps.googleusercontent.com',
    iosBundleId: 'tn.hazem.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdNrWPwlE8x6a3A7SeAhYlnykDfQpf55s',
    appId: '1:57355257284:ios:3c16705b80d95dfcdc1091',
    messagingSenderId: '57355257284',
    projectId: 'mynotes-hazem-windows',
    storageBucket: 'mynotes-hazem-windows.appspot.com',
    iosClientId: '57355257284-s3rp9ot7m69d8g09nmrsnc1p9s8n3ku0.apps.googleusercontent.com',
    iosBundleId: 'tn.hazem.mynotes',
  );
}
